# Base configs
baseurl: "http://scubestudios.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by S-Cube Stdios"
subtitle: "See the world through my lenses!"
author: "Sachin Gaikwad"
header:
 title: "Photography"
 subtitle: "by S-Cube Studios"
footer:
 name: "Hey there, Welcome to S-Cube Studios"
 bio: "All About Photography , FILM , EDITING."

web_design: "S-Cube"
social_urls:
  facebook: "https://www.facebook.com/scubestudios"

